### ISSUE TITLE
Estudar sobre o Roadmap

### ISSUE THREAD

**Issue by JoaoSchmitz** [fga-eps-mds/2022-1-Squad3#12]
## Descrição

Estudar e dar os primeiros passos para que, depois, o Roadmap do projeto possa ser implementado.

## Tarefas

- [x] Estudar o que é o Roadmap.
- [x] Escolher opções de Template para o Roadmap.
- [x] Visualizar Roadmaps de projetos anteriores para referência.

## Critérios de Aceitação

- [x] Ter as opções de Template disponíveis para visualização.

## Informação adicional

Roadmaps de projetos anteriores:
https://fga-eps-mds.github.io/2019.2-Acacia/#/product_roadmap
https://fga-eps-mds.github.io/2019.1-ADA/#/docs/roadmaps/product_roadmap
https://fga-eps-mds.github.io/2020.1-VC_Usuario/#/docs/Roadmap

**Comment by JoaoSchmitz** [comment]
O que é Roadmap e como fazer:

https://endeavor.org.br/estrategia-e-gestao/roadmap/

"Na prática, um roadmap é uma espécie de linha do tempo visual, abaixo da qual deverão ser relacionados todos os itens que farão parte do crescimento do produto, por data."

**Comment by JoaoSchmitz** [comment]
Opções de Templates:

https://fga-eps-mds.github.io/2019.1-ADA/docs/assets/img/roadmaps/product_roadmap_v2.png
https://fga-eps-mds.github.io/2020.1-VC_Usuario/docs/Imagens/Roadmap/Roadmap-vamos-cuidar.png
https://i.imgur.com/bgqP05I.png
https://www.alura.com.br/artigos/assets/como-criar-roadmap-de-produtos/imagem1.png

Caso a equipe julgue necessário ou encontre um melhor, o Roadmap pode usar outro Template fora os aqui presentes.
